# Generated by Django 5.1 on 2024-08-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_image_image_processedimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="folder",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
