# Generated by Django 5.1 on 2024-10-11 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_processedimage_contour_image_and_more"),
        ("ml_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mlresult", old_name="processed_at", new_name="created_at",
        ),
        migrations.RemoveField(model_name="mlresult", name="image",),
        migrations.RemoveField(model_name="mlresult", name="results",),
        migrations.AddField(
            model_name="mlresult",
            name="best_match_grade",
            field=models.CharField(default="N/A", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="mlresult",
            name="best_match_similarity_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="mlresult",
            name="best_match_standard_image",
            field=models.CharField(default="Standard Image", max_length=255),
        ),
        migrations.AddField(
            model_name="mlresult",
            name="folder",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="app.folder"
            ),
        ),
        migrations.AddField(
            model_name="mlresult",
            name="image_name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="mlresult",
            name="num_detections",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="mlresult",
            name="result_image",
            field=models.ImageField(blank=True, null=True, upload_to="ml_results/"),
        ),
    ]
